name: app_01
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  provider: ^6.0.0
  screen_protector: ^1.4.1
  dio: ^5.9.0
  http: ^1.2.2
  device_info_plus: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
